sftp_account_assume_role = "arn:aws:iam::124994850539:role/OrganizationAccountAccessRole"
permanent_storage_assume_role = "arn:aws:iam::648237614702:role/OrganizationAccountAccessRole"
aws_region = "ap-southeast-1"
transfer_endpoint_type = "PUBLIC"
transfer_server_name = "terratest-sftp-server-terratest"
transfer_server_s3_bucket_name = "name"
transfer_server_vpc_id = "vpc-001a8eeb991091c73"
