name: terratest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "ap-southeast-1"
jobs:
  test_and_release_job:
    name: terratest
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Go (1.16)
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      - name: Get Go dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Run 'go test -v -timeout 30m'
        run: |
          cd test
          go test -v -timeout 30m

      - name: release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git@7.0.18
            @semantic-release/exec@3.3.8
            @semantic-release/changelog@3.0.0
